export default {
  HOME : '/',
  LEADERBOARD : '/leaderboard',
  TOURNEYS : '/tournaments',
  FEEDS : '/feeds',
  ADD_TOURNEY : '/admin/addtourney',
  ADD_PUBLIC_TOURNEY : '/addtourney',
  ADD_FEED : '/admin/addfeed',
  FEEDBACK : '/feedback',
  POSTS : '/posts',
  ADMIN : '/admin',
  LINKS : '/links',
  PLAYERCARDBG : '/playercardbg',
  FEATURES : '/features',
}
