export default {
  LOGIN : 'LOGIN',
  LOGOUT : 'LOGOUT',
  LOAD_LEADERBOARD : 'LOAD_LEADERBOARD',
  ADD_TOURNEY : 'ADD_TOURNEY',
  DELETE_TOURNEY : 'DELETE_TOURNEY',
  LOAD_TOURNEYS : 'LOAD_TOURNEYS',
  ADD_FEED : 'ADD_FEED',
  DELETE_FEED: 'DELETE_FEED',
  LOAD_FEEDS: 'LOAD_FEEDS',
  ROSHAN_UPDATED : 'ROSHAN_UPDATED',
  LOAD_PUBLIC : 'LOAD_PUBLIC'
}
